version: "3.4"

services:
  php:
    container_name: php
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - SERVER_NAME=localhost #helps IDE to map files for remote debugging with xdebug
      - SERVER_PORT=80 #helps IDE to map files for remote debugging with xdebug
    volumes:
      - ./:/var/www
      - /usr/local/etc/php/conf.d
      - ./docker/php/php:/usr/local/etc/php
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    environment:
      POSTGRES_DB: "app"
      POSTGRES_PASSWORD: "!ChangeMe!"
      POSTGRES_USER: "app"
    volumes:
      - dbdata:/var/lib/postgresql/data:rw
    ports:
      - "15432:5432"

volumes:
  dbdata:
