coop_tilleuls_forgot_password:
    resource: "@CoopTilleulsForgotPasswordBundle/Resources/config/routing.xml"
    prefix:   /forgot-password

#the bundle has trailing slash for the reset route, so adding alias here, i.e. /forgot-password/ as /forgot-password
coop_tilleuls_forgot_password_reset:
    path: /forgot-password
    controller: 'coop_tilleuls_forgot_password.controller.reset_password'



